(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Clear["Global`*"];


Clear["Global`*"];
SetDirectory@NotebookDirectory[];
SetOptions[Notebooks["apportionment_local.nb"][[1]],AutoGeneratedPackage->Automatic]


statesByAbbreviation = CloudGet["https://www.wolframcloud.com/objects/1a4bfb31-d5d4-49e3-9e04-4cf80e1fae1b"];
(* statesByAbbreviation = Import["./data/state_population_reps_evs.wl"]; *)


stateAbbrs = Keys@statesByAbbreviation;


priorityHuntingtonHill[stateAbbr_, stateEVs_] := 
	1.0 * statesByAbbreviation[stateAbbr]["population_decennial"]["2010"] / 
	Sqrt[stateEVs * (stateEVs + 1)]


(* We need a list of state abbreviations without DC since it is not factored into allocation -- "Taxation Without Representation!" *)
stateAbbrs50 = Select[stateAbbrs, # != "DC"&];

AllocateOne[evs_, priorities_, priorityFunc_:priorityHuntingtonHill] := (
	topPriority = First[Keys[Reverse[Sort[priorities]]]];
	updatedPriorities = priorities;
	updatedEVs = evs;
	updatedEVs[topPriority] += 1;
	updatedPriorities[topPriority] = priorityFunc[topPriority, updatedEVs[topPriority]];
	{ updatedEVs, updatedPriorities }
);

calculateAllocations[total_:435, min_:1, priorityFunc_:priorityHuntingtonHill]:= (
	stateEVs = AssociationThread[stateAbbrs50, ConstantArray[min, 50]];
	statePriorities = AssociationThread[stateAbbrs50, priorityFunc[#, 1]& /@ stateAbbrs50];
	While[Total@stateEVs < total, { stateEVs, statePriorities } = AllocateOne[stateEVs, statePriorities, priorityFunc]];
	KeySort@stateEVs
);


calculatedReps = bigHouse;


houseOfRepresentatives2010 = AssociationThread[
	stateAbbrs50,
	statesByAbbreviation[#]["representatives"]["2010"]& /@ stateAbbrs50
];


statePopulations = AssociationThread[
	stateAbbrs50,
	statesByAbbreviation[#]["population_decennial"]["2010"]& /@ stateAbbrs50
];


peoplePerRepresentative[allocation_] := (
	perRep = AssociationThread[
		Keys@allocation,
		Round[statePopulationsWithUS[#] / allocation[#] * 1.0]& /@ Keys@allocation
	]
)


(* base values *)
headers = Style[#, TextAlignment -> Center, FontSize->12]& /@ { "State", "House", "Calculated", "Delta", "Per Rep\nHouse", "Per Rep\nCalculated" };
stateLabels = Keys@calculatedReps;
diffs = calculatedReps - houseOfRepresentatives2010;


(* colors *)
green = RGBColor["#47C045"];
purple = RGBColor["#E165FA"];
orange = RGBColor["#FF703B"];
maxReps = Max[{Max[calculatedReps], Max[houseOfRepresentatives2010]}];
maxDiff = Max[Abs /@ diffs];
colorScaleReps = Function[d, Blend[Transpose[{{-maxReps / 4, maxReps}, { White, orange }}], d]];
colorScaleDiff = Function[d, Blend[Transpose[{{-maxDiff, 0, maxDiff}, { green, White, purple }}], d]];
colorFunctionReps = Function[v, colorScaleReps[v]];
colorFunctionDiff = Function[v, colorScaleDiff[v]];


Grid


(* colorFunctionReps = Function[v, If[v == houseOfRepresentatives2010["US"], Yellow, colorScaleReps[v]]]; *)


ratioHouse = peoplePerRepresentative[houseOfRepresentatives2010];
ratioCalculated = peoplePerRepresentative[calculatedReps];


(* bar charts *)
bcHouse = BarChart[houseOfRepresentatives2010[#]& /@ stateLabels,
	ChartLabels->stateLabels,
	BarOrigin->Left, GridLines->Automatic, ImageSize->{200, 800}, AspectRatio->4,
	PlotRangePadding -> { 10, 0 }, PlotRange->{ Automatic, Max[calculatedReps] },
	ColorFunctionScaling -> False,
	ColorFunction->colorFunctionReps
];

bcCalculated = BarChart[calculatedReps[#]& /@ stateLabels,
	ChartLabels->stateLabels,
	BarOrigin->Left, GridLines->Automatic, ImageSize->{200, 800}, AspectRatio->4,
	PlotRangePadding -> { 10, 0 }, PlotRange->{ Automatic, Max[calculatedReps] },
	ColorFunctionScaling -> False,
	ColorFunction->colorFunctionReps
];

Row[{bcHouse, bcCalculated}, BaselinePosition->Top]



(* data *)
headers = Style[#, TextAlignment -> Center, FontSize->12]& /@ { "State", "House", "Calculated", "Delta", "Per Rep\nHouse", "Per Rep\nCalculated" };
stateLabelsWithUS = Append[Keys@calculatedReps, "US"];
houseOfRepresentatives2010WithUS = Append[houseOfRepresentatives2010, "US" -> Total@houseOfRepresentatives2010];
calculatedRepsWithUS = Append[calculatedReps, "US" -> Total@calculatedReps];
diffsWithUS = calculatedRepsWithUS - houseOfRepresentatives2010WithUS;
statePopulationsWithUS = Append[statePopulations, "US" -> Total@statePopulations];
ratioHouseWithUS = peoplePerRepresentative[houseOfRepresentatives2010WithUS];
ratioCalculatedWithUS = peoplePerRepresentative[calculatedRepsWithUS];





		ChartLabels->labels, GridLines->Automatic, ImageSize->{800, Automatic}, AspectRatio->1/4,
		PlotRangePadding -> { -1, 0 }, PlotRange->{ Automatic, Max[sorted] * 1.1 }, ChartStyle->Purple,
		ColorFunctionScaling -> False,
		ColorFunction->colorFunction,
		PlotLabel-> Column[{
			Style[ToString@total <> " Seats", FontSize->20],
			Style["Target: " <> ToString@NumberForm[ideal, DigitBlock -> 3] <> " people per representative", FontSize->14],
			Style["Standard Deviation: " <> ToString[sdPrint], FontSize->14],
			Style["Coefficient of Variation: " <> ToString@cov, FontSize->14]
		}, Alignment->Center],
		BarSpacing->None


total = Total@allocation
ratioWithUS = Append[ratio, "US" -> ideal];


(* colors *)
	sd = StandardDeviation[ratio] * 1.0;
	cov = sd / Mean@ratio;
	sdPrint = NumberForm[Round[sd], DigitBlock->3];






colorScaleReps = Function[d, Blend[Transpose[{{-1, maxReps}, { White, orange }}], d]];
colorScaleDiff = Function[d, Blend[Transpose[{{-maxDiff, 0, maxDiff}, { green, White, purple }}], d]];

header = Item[#, Alignment -> Right, ItemSize->{9, 1.5}]& /@ { "State", "House", "Input", "Delta" };
houseOfRepresentatives2010Items = Item[houseOfRepresentatives2010[#], Background->colorScaleReps[#]]& /@ Keys@houseOfRepresentatives2010;
calculatedRepItems = Item[#, Background->colorScaleReps[#]]& /@ calculatedReps;
diffItems = Item[#, Background->If[# == 0, White, colorScaleDiff[#]], ItemSize->{2,1.5}]& /@ diffs;
totals = Item[Style[#, Bold], ItemSize->{4.8, 1.5}]& /@ { "Total", Total@houseOfRepresentatives2010, Total@calculatedEVs, Total@diffs }





compareAllocations[calculatedEVs_] := (
	diffs = calculatedEVs - houseOfRepresentatives2010;
	
	(* colors *)
	maxEV = Max[{Max[calculatedEVs], Max[houseOfRepresentatives2010]}];
	maxDiff = Max[Abs /@ diffs];
	colorScaleEV = ColorData[{"SiennaTones", "Reverse"}, Rescale[#1, {0, maxEV * 1.25}]]&;
	
	green = RGBColor["#47C045"];
	purple = RGBColor["#E165FA"];
	colorScaleDiff = Function[d, Blend[Transpose[{{-maxDiff, 0, maxDiff}, { green, White, purple }}], d]];

	(* cells as items *)
	header = Item[#, Alignment -> Right, ItemSize->{9, 1.5}]& /@ { "state", "actual reps", "calculated reps", "difference" };
	houseOfRepresentatives2010Items = Item[#, Background->colorScaleEV[#]]& /@ houseOfRepresentatives2010;
	calculatedEVItems = Item[#, Background->colorScaleEV[#]]& /@ calculatedEVs;
	diffItems = Item[#, Background->If[# == 0, White, colorScaleDiff[#]], ItemSize->{2,1.5}]& /@ diffs;
	totals = Item[Style[#, Bold], ItemSize->{4.8, 1.5}]& /@ { "Total", Total@houseOfRepresentatives2010, Total@calculatedEVs, Total@diffs };

	(* build rows of grids *)
	columns = { Keys@houseOfRepresentatives2010, Values@houseOfRepresentatives2010Items, Values@calculatedEVItems, Values@diffItems };	
	parts = First@Partition[Map[Append[columns[[#]], totals[[#]]]&, Range[4]], { 4, UpTo@13 }];
	rows = Map[Flatten, Transpose[{ header, # }]& /@ parts, {2}];
	Column[Grid[#, Frame -> All, ItemSize->All]& /@ rows, Spacings->0.25]
)


visualizeRatio[allocation_] := (
	ratio = peoplePerRepresentative[allocation];
	total = Total@allocation;
	ideal = Round[totalUSPopulation / total];
	ratioWithUS = Append[ratio, "US" -> ideal];
	sd = StandardDeviation[ratio] * 1.0;
	cov = sd / Mean@ratio;
	sdPrint = NumberForm[Round[sd], DigitBlock->3];

	colorScale = ColorData["Rainbow", Rescale[#1, MinMax@ratio]]&;
	colorFunction = Function[v, If[v == ideal, Yellow, colorScale[v]]];

	sorted = Sort@ratioWithUS;
	allocationsWithUS = Append[allocation, "US" -> "NA"];
	
	labels = Placed[Style[Rotate[# <> ": " <> ToString@allocationsWithUS[#], Pi/2],
		If[# == "US", Bold, Plain], FontSize->8, If[# == "US", Black, White]]& /@ Keys@sorted, Top];
			
	BarChart[sorted,
		ChartLabels->labels, GridLines->Automatic, ImageSize->{800, Automatic}, AspectRatio->1/4,
		PlotRangePadding -> { -1, 0 }, PlotRange->{ Automatic, Max[sorted] * 1.1 }, ChartStyle->Purple,
		ColorFunctionScaling -> False,
		ColorFunction->colorFunction,
		PlotLabel-> Column[{
			Style[ToString@total <> " Seats", FontSize->20],
			Style["Target: " <> ToString@NumberForm[ideal, DigitBlock -> 3] <> " people per representative", FontSize->14],
			Style["Standard Deviation: " <> ToString[sdPrint], FontSize->14],
			Style["Coefficient of Variation: " <> ToString@cov, FontSize->14]
		}, Alignment->Center],
		BarSpacing->None
	]
)


colorScaleReps = ColorData[{"SiennaTones", "Reverse"}, Rescale[#1, {0, maxEV * 1.25}]]&;



visualizeRatio[allocation_] := (
	ratio = peoplePerRepresentative[allocation];
	total = Total@allocation;
	ideal = Round[totalUSPopulation / total];
	ratioWithUS = Append[ratio, "US" -> ideal];
	sd = StandardDeviation[ratio] * 1.0;
	cov = sd / Mean@ratio;
	sdPrint = NumberForm[Round[sd], DigitBlock->3];

	colorScale = ColorData["Rainbow", Rescale[#1, MinMax@ratio]]&;
	colorFunction = Function[v, If[v == ideal, Yellow, colorScale[v]]];

	sorted = Sort@ratioWithUS;
	allocationsWithUS = Append[allocation, "US" -> "NA"];
	
	labels = Placed[Style[Rotate[# <> ": " <> ToString@allocationsWithUS[#], Pi/2],
		If[# == "US", Bold, Plain], FontSize->8, If[# == "US", Black, White]]& /@ Keys@sorted, Top];
			
	BarChart[sorted,
		ChartLabels->labels, GridLines->Automatic, ImageSize->{800, Automatic}, AspectRatio->1/4,
		PlotRangePadding -> { -1, 0 }, PlotRange->{ Automatic, Max[sorted] * 1.1 }, ChartStyle->Purple,
		ColorFunctionScaling -> False,
		ColorFunction->colorFunction,
		PlotLabel-> Column[{
			Style[ToString@total <> " Seats", FontSize->20],
			Style["Target: " <> ToString@NumberForm[ideal, DigitBlock -> 3] <> " people per representative", FontSize->14],
			Style["Standard Deviation: " <> ToString[sdPrint], FontSize->14],
			Style["Coefficient of Variation: " <> ToString@cov, FontSize->14]
		}, Alignment->Center],
		BarSpacing->None
	]
)



